import Link from 'next/link'
import React from 'react'

function Definitions() {
  return (
    <>
        <div className='2xl:text-[18px] xl:text-[13.5px] text-[12px] text-[#777777] [&_a]:text-[#3563E9] [&_a]:font-medium [&_a]:underline'>
            SERVICE means the <Link href='http://www.eltedge.io' target='_blank'>http://www.eltedge.io</Link> website operated by eLogic Engineering Services Private Limited.<br/>
            PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br/>
            USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit). COOKIES are small files stored on your device (computer or mobile device).<br/>
            DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.<br/>
            DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.<br/>
            DATA SUBJECT is any living individual who is the subject of Personal Data.<br/>
            THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.
        </div>
    </>
  )
}

export default Definitions