import type { Metadata } from "next";
import RootLayout from "./rootLayout";

export const metadata: Metadata = {
  title: "ElogcTech",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}
